const properties = [
	{
		id: 1,
		name: 'Property One',
		address: 'Feldhofstrasse 66',
		type: 'investment',
		market: 'buy',
		city: 'Zurich',
		canton: 'zug',
		size: 2000 + ' sq meters',
		price: 1 + ' Million',
		image1: 'CommunityExterior3.jpg',
		image2: 'home2.jpg',
		image3: 'home3.jpg',
		docs: 'docs/houseDocs.pdf'
	},
	{
		id: 2,
		name: 'Property 2',
		address: 'Feldhofstrasse 66',
		type: 'residential',
		market: 'buy',
		city: 'Zurich',
		canton: 'zurich',
		size: 1300 + ' sq meters',
		price: 650000,
		image1: 'home2.jpg',
		image2: 'CommunityExterior3.jpg',
		image3: 'home3.jpg',
		docs: 'docs/houseDocs.pdf'
	},
	{
		id: 3,
		name: 'Property Three',
		address: 'Feldhofstrasse 90',
		type: 'investment',
		market: 'rent',
		city: 'Zurich',
		canton: 'bern',
		size: 900 + ' sq meters',
		price: 2 + ' Million',
		image1: 'home3.jpg',
		image2: 'home2.jpg',
		image3: 'CommunityExterior3.jpg',
		docs: 'docs/houseDocs.pdf'
	},
	{
		id: 4,
		name: 'Property 4',
		address: 'Feldhofstrasse 16',
		type: 'investment',
		market: 'buy',
		city: 'zurich',
		canton: 'zurich',
		size: 800 + ' sq meters',
		price: 1.5 + ' Million',
		image1: 'CommunityExterior3.jpg',
		image2: 'home2.jpg',
		image3: 'home3.jpg',
		docs: 'docs/houseDocs.pdf'
	},
	{
		id: 5,
		name: 'Property 4',
		address: 'Feldhofstrasse 16',
		type: 'residential',
		market: 'buy',
		city: 'Zurich',
		canton: 'zurich',
		size: 1034 + ' sq meters',
		price: 1.5 + ' Million',
		image1: 'home4.jpg',
		image2: 'home2.jpg',
		image3: 'home3.jpg',
		docs: 'docs/houseDocs.pdf'
	},
	{
		id: 5,
		name: 'Property 4',
		address: 'Lake Bend Rd 49',
		type: 'residential',
		market: 'rent',
		city: 'bern',
		canton: 'zurich',
		size: 1034 + ' sq meters',
		price: 2 + ' Million',
		image1: 'home4.jpg',
		image2: 'home2.jpg',
		image3: 'home3.jpg',
		docs: 'docs/houseDocs.pdf'
	}
];
